manifest:
  self:
    path: .

  projects:
  - name: micro_ros_zephyr_module
    url: https://github.com/micro-ROS/micro_ros_zephyr_module
    revision: jazzy
    path: modules/micro_ros_zephyr_module
    import: modules/libmicroros
